Latestfile
group-number5/RN101-class pull request #3
Opened 2020-08-02 17:31 UTC by kimkihoon0515

오늘까지한 최종본 파일입니다

2020-08-02 17:42 UTC, jmchoi1225 approved these changes

2020-08-04 00:45 UTC, jmchoi1225 requested changes
android 폴더가 추가되었는데 나중에 merge할 때 이 android 폴더의 변경사항이 적용되지 않도록 해주세요.

2020-08-05 07:02 UTC, kimkihoon0515 commented
그 이모티콘을 생성하려면 android에 저 설정을 해줘야합니다

2020-08-05 07:18 UTC, jmchoi1225 approved these changes
좋아요

2020-08-05 10:16 UTC, merged